### ISSUE TITLE
BetterEnd config does not work

### ISSUE THREAD

**Issue by arrrnmp** [PolyhedralDev/TerraDefaultConfig#64]
When enabling the betterend config pack shows up an error related to something of the biome Shattered End and it's trees.
Minecraft Server Version: 1.17.1
Software: Purpur (tried on Paper & Tuinity, and doesn't seem to work, as both show up the same error)

**Comment by Roan-V** [comment]
![image](https://user-images.githubusercontent.com/77012724/126876886-061ea080-8f2a-4bea-b4f7-8acc463bb077.png)

**Comment by arrrnmp** [comment]
I know it is in early development, that's why I'm just telling that it is broken, so they can fix it lol.

**Comment by Sancires** [comment]
We're aware it's not in a working state. That's why there's a warning.

**Comment by alsoGAMER** [comment]
> When enabling the betterend config pack shows up an error related to something of the biome Shattered End and it's trees.
> Minecraft Server Version: 1.17.1
> Software: Purpur (tried on Paper & Tuinity, and doesn't seem to work, as both show up the same error)

Related to this issue, here the full log:
```
[21:53:28 ERROR]: [Terra] Failed to load config pack from ZIP archive "plugins/Terra/packs/betterend.zip"
[21:53:28 WARN]: com.dfsek.tectonic.exception.LoadException: Failed to load config with ID "SHATTERED_FOREST": Failed to load value "trees" to field "trees" in config "shattered_forest.yml": No such com.dfsek.terra.api.platform.world.Tree matching "SHATTERED_SMALL" was found in this registry.
[21:53:28 WARN]: 	at com.dfsek.tectonic.abstraction.AbstractConfigLoader.loadConfigs(AbstractConfigLoader.java:83)
[21:53:28 WARN]: 	at com.dfsek.terra.config.pack.ConfigPack.lambda$load$17(ConfigPack.java:254)
[21:53:28 WARN]: 	at com.dfsek.terra.config.fileloaders.Loader.then(Loader.java:27)
[21:53:28 WARN]: 	at com.dfsek.terra.config.pack.ConfigPack.load(ConfigPack.java:254)
[21:53:28 WARN]: 	at com.dfsek.terra.config.pack.ConfigPack.<init>(ConfigPack.java:190)
[21:53:28 WARN]: 	at com.dfsek.terra.registry.master.ConfigRegistry.load(ConfigRegistry.java:46)
[21:53:28 WARN]: 	at com.dfsek.terra.registry.master.ConfigRegistry.loadAll(ConfigRegistry.java:36)
[21:53:28 WARN]: 	at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:184)
[21:53:28 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:53:28 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[21:53:28 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[21:53:28 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[21:53:28 WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[21:53:28 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:277)
[21:53:28 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[21:53:28 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[21:53:28 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[21:53:28 WARN]: Caused by: com.dfsek.tectonic.exception.LoadException: Failed to load value "trees" to field "trees" in config "shattered_forest.yml": No such com.dfsek.terra.api.platform.world.Tree matching "SHATTERED_SMALL" was found in this registry.
[21:53:28 WARN]: 	at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:185)
[21:53:28 WARN]: 	at com.dfsek.tectonic.abstraction.AbstractConfigLoader.loadConfigs(AbstractConfigLoader.java:81)
[21:53:28 WARN]: 	... 16 more
[21:53:28 WARN]: Caused by: com.dfsek.tectonic.exception.LoadException: No such com.dfsek.terra.api.platform.world.Tree matching "SHATTERED_SMALL" was found in this registry.
[21:53:28 WARN]: 	at com.dfsek.terra.registry.OpenRegistry.load(OpenRegistry.java:28)
[21:53:28 WARN]: 	at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:217)
[21:53:28 WARN]: 	at com.dfsek.terra.config.loaders.ProbabilityCollectionLoader.load(ProbabilityCollectionLoader.java:32)
[21:53:28 WARN]: 	at com.dfsek.terra.config.loaders.ProbabilityCollectionLoader.load(ProbabilityCollectionLoader.java:13)
[21:53:28 WARN]: 	at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:217)
[21:53:28 WARN]: 	at com.dfsek.terra.config.loaders.config.TreeLayerLoader.load(TreeLayerLoader.java:25)
[21:53:28 WARN]: 	at com.dfsek.terra.config.loaders.config.TreeLayerLoader.load(TreeLayerLoader.java:17)
[21:53:28 WARN]: 	at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:217)
[21:53:28 WARN]: 	at com.dfsek.tectonic.loading.loaders.generic.ArrayListLoader.load(ArrayListLoader.java:28)
[21:53:28 WARN]: 	at com.dfsek.tectonic.loading.loaders.generic.ArrayListLoader.load(ArrayListLoader.java:17)
[21:53:28 WARN]: 	at com.dfsek.tectonic.loading.ConfigLoader.loadType(ConfigLoader.java:217)
[21:53:28 WARN]: 	at com.dfsek.tectonic.loading.ConfigLoader.load(ConfigLoader.java:169)
[21:53:28 WARN]: 	... 17 more
```

**Comment by Roan-V** [comment]
Yes.
As mentioned before, the BetterEnd pack is nowhere near usable atm.
It's still in development, but dfsek's time is limited and he's currently working on more important stuff, terra 6.0 for example.

As such, this pack is effectively on hiatus, at least until terra 6.0 and the subsequent default pack rewrite are finished
